spring:
  application:
    name: JRTP701-CorrespondenceAPI
# for data source 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jrtp701-ish-db
    username: root
    password: root
    
# jpa hibernate property
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: manishkumarhn7114@gmail.com
    password: Manish@7114
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
