spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: JRTP701-CorrespondenceAPI
#  datasource:
#   driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    url: jdbc:mysql:///jrtp701-ish-db
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
eureka:
  client:
    service-url:
      defrault-zone: http://localhost:8761/eureka
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: manishkumarhn7114@gmail.com
    password: jnzg orrv ftmh nkwm
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 7075
