server:
  port: 7076
spring:
  config:
    import: optional:configserver:http://localhost:8888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  application:
    name: JRTP701-BIService
#  datasource:
#   driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    url: jdbc:mysql:///jrtp701-ish-db
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
eureka:
  client:
    service-url:
      defrault-zone: http://localhost:8761/eureka
