server:
  port: 7074
spring:
  application:
    name: JRTP701-AdminService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql:///jrtp701-ish-db
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

plan:
  module:
   messages:
    save-success: Plan is saved with id value
    save-failure: Plan is not saved with id value
    find-by-id-failure: Plan is not found
    update-success: Plan is updated
    update-failure: Plan is not found for updation
    delete-success: Plan is deleted
    delete-failure: Plan is not found
    status-change-success: Plan Status is changed
    status-change-failure: Plan is not found for status change
    